### ISSUE TITLE
Content Security Policy warning in Safari

### ISSUE THREAD

**Issue by Twissi** [hackerinnen/hackerinnen-form#7]
Looks like csp is not configured correctly. Seeing this warning when hitting `Reset form` on the page.

![Screenshot 2019-10-19 at 18 31 54](https://user-images.githubusercontent.com/261567/67148321-d8f1f180-f29e-11e9-9b49-1bbf9b5a5105.png)

**Comment by camdunne** [comment]
@Twissi hi I would love to solve this and submit a PR. Thanks!

**Comment by Twissi** [comment]
@camdunne 💟sounds awesome!
